site_name: Imagededup
site_author: idealo Data Science Team

nav:
    - Home: index.md
    - User Guide:
        - Finding duplicates: user_guide/finding_duplicates.md
        - Encoding generation: user_guide/encoding_generation.md
        - Custom Models: user_guide/custom_model.md
        - Plotting duplicates: user_guide/plotting_duplicates.md
        - Evaluating performance: user_guide/evaluating_performance.md
        - Benchmarks: user_guide/benchmarks.md
    - API reference:
        - Methods:
            - CNN: methods/cnn.md
            - Hashing: methods/hashing.md
        - Evaluation:
            - Evaluation: evaluation/evaluation.md
        - Utils:
            - Plot duplicates: utils/plotter.md
            - Custom Models: utils/models.md
    - Example:
        - CIFAR10 deduplication: examples/CIFAR10_deduplication.md
    - Contribution: CONTRIBUTING.md
    - License: LICENSE.md
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'img/logo.svg'
  favicon: 'img/favicon.ico'

repo_name: 'idealo/imagededup'
repo_url: 'https://github.com/idealo/imagededup'

google_analytics:
  - 'UA-137434942-4'
  - 'auto'

markdown_extensions:
  - codehilite
